#!/usr/bin/env bash
# ValuationSuite — project launcher
# Generated by install.sh on 2026-05-20.
# Re-run install.sh if you move the project directory.
# KMP_DUPLICATE_LIB_OK: prevents SIGSEGV when brew's libomp and PyTorch's
# bundled libiomp5 are both present on the same macOS machine.
export KMP_DUPLICATE_LIB_OK=TRUE
exec "/Users/pzuzarte/GitHub/valuationScripts/.venv/bin/python" "/Users/pzuzarte/GitHub/valuationScripts/app.py" "$@"
