#!/usr/bin/env bash
# ValuationSuite — project launcher
# Generated by install.sh on 2026-03-20.
# Re-run install.sh if you move the project directory.
exec "/Users/pzuzarte/GitHub/valuationScripts/.venv/bin/python" "/Users/pzuzarte/GitHub/valuationScripts/app.py" "$@"
