#!/usr/bin/env bash
source "$HOME/anaconda3/etc/profile.d/conda.sh" 2>/dev/null || true
conda activate py311 2>/dev/null || true
cd "/Users/pzuzarte/GitHub/valuationScripts"
python "/Users/pzuzarte/GitHub/valuationScripts/app.py"
